# Generated by Django 2.2.4 on 2020-10-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile_pic/header.jpg', null=True, upload_to='images/profile_pic'),
        ),
    ]
