# Generated by Django 2.2.4 on 2020-10-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookuserlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookuserlist',
            name='status',
            field=models.CharField(choices=[('bitenler', 'Bitenler'), ('kutuphane', 'Kütüphanem'), ('okunacaklar', 'Okunacaklar'), ('simdi_okuduklarım', 'SimdiOkuduklarım')], default='dkutuphaneraft', max_length=30),
        ),
    ]
