# Generated by Django 2.2.4 on 2020-10-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20201008_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuserlist',
            name='status',
            field=models.CharField(choices=[('kutuphane', 'Kütüphanem')], default='kutuphane', max_length=10),
        ),
    ]
