# Generated by Django 2.2.4 on 2020-10-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20201009_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknotes',
            name='booksList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
